language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO_VERSION=1.11.25
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6
  - DJANGO_VERSION=3.0b1
install:
  - pip install Django==$DJANGO_VERSION
  - pip install pytest black
  - python setup.py install
script:
  - py.test
  - black . --check
